import"./assets/modulepreload-polyfill-B5Qt9EMX.js";/* empty css                      */const e=[{id:1,img:"./img/in01.jpg",name:"Шуруповерт",price:1500,description:"Мережевий дриль-шуруповерт ТD-30-Надійний помічник для робіт по дому"},{id:2,img:"./img/in02.jpg",name:"Перфоратор",price:3948,description:"Перфоратор бочковий Dnipro-M BH-20 Використовується для сверління"},{id:3,img:"./img/in03.jpg",name:"Шліфмашина",price:1299,description:"Кутова шліфмашина Dnipro-M GS-98 - модель яка поєднує в собі"},{id:4,img:"./img/in04.jpg",name:"Пила",price:11049,description:"Мобільна акумуляторна ланцюгова пила DCS-200BC DUAL"},{id:5,img:"./img/in05.jpg",name:"Рівень",price:897,description:"Рівень серії ProVision виробництва DNIPRO-M"},{id:6,img:"./img/in06.jpg",name:"Тример",price:3699,description:"Тример електричний Dnipro-M 110 призначений для покосу трави"},{id:7,img:"./img/in07.jpg",name:"Мотокоса",price:11049,description:"Мотокоса Dnipro-M 43 призначений для покосу трави, чагарників, бур'янів"},{id:8,img:"./img/in08.jpg",name:"Генератор",price:10890,description:"Бензиновый генератор Dnipro-M GX-25 номінальною потужністю 2,5 кВт"},{id:9,img:"./img/in09.jpg",name:"Культиватор",price:10890,description:"Культиватор електричний Dnipro-M 40"},{id:10,img:"./img/in10.jpg",name:"Лобзик електричний",price:10890,description:"Лобзик електричний Dnipro-M JS-80LX + Набір пиляльних полотен 5 шт"}];console.log(e);const s=document.querySelector(".js-search"),r=document.querySelector(".js-list");console.log(s);function p(i){const n=i.map(({id:o,img:c,name:t})=>`<li data-id=${o} class="js-card">
          <img src="${c}" alt="${t}" width="300">
            <h2>${t}</h2>
                <p><a href="#" class="js-info">More Information</a></p>
            <div>
                <button>Add to favorite</button>
                <button>Add to basket</button>
            </div>
        </li>`).join("");r.innerHTML=n}r.addEventListener("click",d);function d(i){if(i.preventDefault(),i.target.classList.contains("js-info")){const{id:n}=i.target.closest(".js-card").dataset;console.log(n);const o=m(Number(n));console.log(o)}}p(e);function m(i){return e.find(({id:n})=>n===i)}
//# sourceMappingURL=index.js.map
